spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://naregua-server.database.windows.net:1433;databaseName=db_naregua
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    auto-commit: false
    connection-properties: encrypt=true;trustServerCertificate=false;
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.SQLServerDialect

azure:
  storage:
    blob:
      endpoint: https://upload0naregua.blob.core.windows.net/
      account-name: upload0naregua
