spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://naregua-mysql-server.mysql.database.azure.com:3306/db_naregua?serverTimezone=UTC&useSSL=true&requireSSL=false
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    auto-commit: false


  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect

azure:
  storage:
    blob:
      endpoint: https://upload0naregua.blob.core.windows.net/
      account-name: upload0naregua
