name: Build and deploy JAR app to Azure Web App - naregua-backend

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      # Ajuste para o diretório correto no ambiente Ubuntu
      - name: Build with Maven - clean install
        run: |
          cd "SpringBoot - Java"  # Caminho correto para o diretório dentro do repositório
          mvn clean install
        shell: bash

      # Ajuste para o diretório correto no ambiente Ubuntu
      - name: Build with Maven - clean package
        run: |
          cd "SpringBoot - Java"  # Caminho correto para o diretório dentro do repositório
          mvn -B clean package -DskipTests
        shell: bash

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Ajuste para o diretório correto no ambiente Ubuntu
      - name: Run tests with Maven
        run: |
          cd "SpringBoot - Java"  # Caminho correto para o diretório dentro do repositório
          mvn test
        shell: bash

  docker:
    runs-on: ubuntu-latest
    needs:
      - build
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: "./SpringBoot - Java"  # Usando caminho correto
          file: "./SpringBoot - Java/Dockerfile"  # Caminho correto para o Dockerfile
          push: true
          tags: melissaneves/naregua-api:latest
